### ISSUE TITLE
Hasktags fails when fed too many files

### ISSUE THREAD

**Issue by shym** [MarcWeber/hasktags#57]
I ran hasktags on the source of all the packages I installed (4949 .hs files, it seems) and it failed:

```
$ hasktags -c -R -x -o tags <many dirs>
hasktags: libghc-vault-doc/Data-Unique-Really.hs: openBinaryFile: resource exhausted (Too many open files)
```

Without much surprise, it fails at about the 1024th file it tries to open, so it must be forgetting to close the files when they’re done processing.

I’m running hasktags debian unstable package version 0.70.1-1.
I’m pretty sure it was working with a previous version (maybe just the previous in debian, 0.69.3), since I did update successfully my tags database fairly recently.

**Comment by jhenahan** [comment]
Yup, this happened when I switched from strict to lazy bystestrings. It led to much better performance characteristics, but it seems to be a bit sloppier about managing file handles. I'm looking into it, and if I can't find a pleasant solution I may just need to switch back to strict bytestrings, for now.

**Comment by thomie** [comment]
Happens also when running `hasktags -c .` in `ghc` repository.

**Comment by Skyfold** [comment]
The referenced issue is fixed in the Hasktags recent commits (I opened the issue on Haskdogs). The issue was that the latest changes to Hasktags are only in Nixpkgs unstable at the moment. However, I did notice you forgot to update the version number in "hashtags.nix" which is currently at `version = "0.70.0";`. At little know bit of nix magic is `callCabal2nix` which generates what would be "hashtags.nix" when nix-build is invoked, so you never get out of sync with your cabal file.

Here is what your default.nix would look like:
```
{pkgs ? import <nixpkgs> {}, compiler ? "ghc843"}:

let 
  project = pkgs.haskell.packages.${compiler}.callCabal2nix "hasktags" ./. { };
in
  with pkgs.haskell.packages.${compiler};
  { inherit project; }
```
