### ISSUE TITLE
Need a Stack maintainer

### ISSUE THREAD

**Issue by jhenahan** [MarcWeber/hasktags#80]
I haven't used Stack in long enough that I don't feel comfortable attempting to maintain the Stack configuration files in this repo. They will be removed in an upcoming commit. If working on `hasktags` with Stack is important to you, I welcome any and all PRs to support it again.

**Comment by andreasabel** [comment]
I filed https://github.com/commercialhaskell/stackage/pull/6190.
I am happy to serve as stackage maintainer for hasktags.  It seems like no special stack configuration for hasktags is necessary atm.

**Comment by jhenahan** [comment]
You're hired!

**Comment by andreasabel** [comment]
@jhenahan : Can I pass this role over to you now?
Since you are the official maintainer, it makes more sense if you get notifications about outdated dependencies from Stackage, rather than I.  For example:
- https://github.com/commercialhaskell/stackage/issues/7078

Maintaining the `stack.yaml` files is optional.
