### ISSUE TITLE
Infix functions not treated correctly

### ISSUE THREAD

**Issue by adimit** [MarcWeber/hasktags#9]
Functions defined as operators are not caught correctly.

```
(-:) = undefined
(->>) = undefined
```

Should define two infix functions `-:` and `->>`, but `hasktags` only records a single entry of the name `(` with the correct line number of the _first_ such defined function in a file.

**Comment by heroin-moose** [comment]
I can confirm that this issue is still there.

**Comment by jhenahan** [comment]
Just started a new job that leaves me with way more cycles for working on open source, so I'll be looking into these longstanding issues ASAP. Thanks for the ping.

**Comment by jhenahan** [comment]
The first half of this issue is now fixed. Pointfree operator definitions are now tagged properly. Definitions with arguments can be tagged properly, but only with an accompanying type definition. Without getting into some really gross heuristics, I'm not sure that I can devise a method to tag such definitions with the codebase as-is. I'm looking into using the lexer exposed for more recent GHCs to try to support this usecase, though. Feel free to reopen if this is unsatisfactory and you've got an idea.
